### ISSUE TITLE
Compile list of public yoga pose datasets

### ISSUE THREAD

**Issue by joshuacwnewton** [MLH-Fellowship/0.1.2-yoga-pose-detection#3]
### To-do
* [x] Search for public datasets of yoga pose images/videos and compile into lists
* [x] Find specific poses that are common across multiple datasets.
* [x] Discuss whether we need to supplement the images with our own data (e.g. using video frame extraction)
